version: 0.0
os: linux
files:
  - source: /var/lib/jenkins/workspace/dreamztech/java-web-project1/target/java-web-project1.war
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /opt/codedeploy-agent/deployment-root/a0f7f805-3c6a-42e4-af9f-8e1917104b01/d-128UNZVKZ/deployment-archive/var/lib/jenkins/workspace/dreamztech/install_dependencies
      timeout: 300
      runas: root
    - location: /var/lib/jenkins/workspace/dreamztech/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /var/lib/jenkins/workspace/dreamztech/stop_server
      timeout: 300
      runas: root


